events {}

http {
    upstream backends {
        server localhost:5001;
        server localhost:5002;
    }

    server {
        listen 8080;
        location / {
            proxy_pass http://backends;
            proxy_set_header Host $host;
        }
    }
}